name: Publish to GAR
on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      # Workload Identity Federation to GCP
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}   # e.g. projects/123/locations/global/workloadIdentityPools/gh-pool/providers/gh
          service_account: ${{ secrets.GCP_PUBLISH_SA }}                # e.g. tradelab-pypi-publisher@PROJECT.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build distributions
        run: uv build --no-sources

      - name: Publish to GAR
        env:
          # OAuth flow: username must be this literal, password is an access token
          UV_PUBLISH_USERNAME: oauth2accesstoken
          UV_PUBLISH_PASSWORD: ${{ steps.auth.outputs.access_token }}
        run: |
          uv publish --index gar_tradelab --non-interactive -v