name: Publish to GitHub Packages
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Build
        run: uv build

      - name: Publish to GitHub Packages
        env:
          UV_PUBLISH_USERNAME: ${{ github.actor }}
          UV_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: uv publish --publish-url "https://pypi.pkg.github.com/${{ github.repository_owner }}/simple"